### ISSUE TITLE
Are Windows 1703/1709 formats supported?

### ISSUE THREAD

**Issue by lfcnassif** [kacos2000/WindowsTimeline#1]
Project description and Readme.md differs. Are old formats supported? If yes, could you point where are the queries in this repo? I am having "Activity_PackageId table does not exists" issue and I think that is related to a different DB schema...

Thanks in advance

**Comment by kacos2000** [comment]
Try the [Latest EXE](https://github.com/kacos2000/WindowsTimeline/releases/download/v.2.0.81.0/WindowsTimeline.exe) which should work.
