### ISSUE TITLE
nothing happens when it is suggested to download systemSQLlite

### ISSUE THREAD

**Issue by firstrealpresident** [kacos2000/WindowsTimeline#2]
![image](https://user-images.githubusercontent.com/99604366/153760188-924a2f0c-9ad1-41f5-b818-5a8803da3036.png)

**Comment by kacos2000** [comment]
sorry - missed this
You can download & install it from this link:
https://system.data.sqlite.org/blobs/1.0.112.0/sqlite-netFx40-setup-x64-2010-1.0.112.0.exe
